[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "chess-game"
version = "0.1.0"
dependencies = [
    "pydantic>=2",
]

[project.optional-dependencies]
test = ["pytest"]
lint = [
    "mypy",
    "pylint",
    "ruff",
]
dev = [
    "mypy",
    "pylint",
    "pytest",
    "ruff",
]

[tool.pytest.ini_options]
pythonpath = ["."]
addopts = "-v"
markers = [
    "slow: marks tests as slow (deselect with 'not slow')",
]

[tool.ruff]
target-version = "py311"

[tool.ruff.lint]
extend-ignore = ["E741"]

[tool.mypy]
python_version = "3.11"
files = ["chess_game"]
warn_unused_configs = true

[tool.setuptools.packages.find]
include = ["chess_game*"]
namespaces = false
