"""Tuning constants for quiet strategic move-ordering scores.

Extracted from ``ai_move_ordering`` so the ordering knobs live in one place.
``ai_move_ordering`` (and ``ai_check_ordering``) import the constants they use.
"""

QUIET_CASTLING_BONUS = 160
QUIET_PASSED_PAWN_PUSH_BONUS = 90
QUIET_KING_CENTRALIZATION_BONUS = 18
QUIET_HEAVY_PIECE_PRESSURE_BONUS = 24
QUIET_CENTRALIZATION_BONUS = 12
QUIET_KING_CUTOFF_BONUS = 32
QUIET_ROOK_BEHIND_PASSER_BONUS = 40
QUIET_LUFT_BONUS = 16
QUIET_WORST_PIECE_BONUS = 18
QUIET_BLOCKADE_BONUS = 28
QUIET_MAJOR_TRADE_OFFER_BONUS = 26
QUIET_KING_REFINEMENT_BONUS = 10
QUIET_USEFUL_CHECK_BONUS = 34
QUIET_URGENT_LUFT_BONUS = 24
QUIET_H_EXPOSURE_LUFT_BONUS = 40
QUIET_PROPHYLACTIC_LUFT_BONUS = 32
QUIET_CONTEST_ATTACK_FILE_BONUS = 44
QUIET_DANGER_RELIEF_BONUS = 52
QUIET_ENTRY_SQUARE_BONUS = 28
QUIET_ADD_DEFENDER_BONUS = 22
QUIET_RECONNECT_DEFENDER_BONUS = 18
QUIET_RESTORE_BACK_RANK_BONUS = 26
QUIET_NEGLECT_DANGER_PENALTY = 34
QUIET_PLAN_RELIEF_BONUS = 8
QUIET_PLAN_NEGLECT_PENALTY = 7
QUIET_ACTIVITY_LINE_PRESSURE_BONUS = 16
QUIET_ACTIVITY_COORDINATION_BONUS = 14
QUIET_ACTIVITY_SIMPLIFY_BONUS = 18
QUIET_ACTIVITY_CHASE_PENALTY = 22
QUIET_ACTIVITY_REPEAT_PENALTY = 28
QUIET_ACTIVITY_LOOSEN_PENALTY = 18
QUIET_CHECK_MATE_NET_BONUS = 64
QUIET_CHECK_MATERIAL_BONUS = 30
QUIET_CHECK_DRIVING_BONUS = 22
QUIET_CHECK_SIMPLIFY_BONUS = 16
QUIET_BISHOP_PASSIVE_RETREAT_PENALTY = 24
QUIET_CHECK_SHRINK_BOX_BONUS = 16
QUIET_CHECK_BREAK_DEFENDER_BONUS = 12
QUIET_EMPTY_CHECK_PENALTY = 40
QUIET_EASY_SHUFFLE_CHECK_PENALTY = 20
QUIET_SELF_EXPOSING_CHECK_PENALTY = 22
ENDGAME_ORDER_MAX_NON_KING_PIECES = 8
_ADVANTAGE_PRESERVATION_HANGING_PENALTY = 30
_ADVANTAGE_PRESERVATION_MIN_LEAD = 400  # 4 pawns
_KNIGHT_THREATENS_MINOR_BONUS = 12
