"""Tuning constants for winning-endgame conversion guidance.

Extracted from ``conversion_guidance`` so the conversion knobs live in one place.
``conversion_guidance`` (and ``conversion_low_material``) import the constants they
use.
"""

from chess_game.chess.evaluation_tables import MATERIAL_VALUES
from chess_game.chess.types import PieceType

_MAX_NON_KING_PIECES = 5
_MAX_HEAVY_CONVERSION_NON_KING_PIECES = 22
_MIN_HEAVY_CONVERSION_LEAD = MATERIAL_VALUES[PieceType.BISHOP]
_EVAL_SCALE = 3
_ORDER_SCALE = 4
_ROOT_SCALE = 6
_CHECK_DRIFT_PENALTY = 36
_KING_ACTIVATION_BONUS = 10
_PASSER_ADVANCE_BONUS = 30
_MAIN_PASSER_ROOT_BONUS = 34
_TRADE_QUALITY_BONUS = 18
_PASSER_SUPPORT_BONUS = 10
_PROMOTION_LANE_SUPPORT_BONUS = 12
_PROMOTION_SQUARE_SUPPORT_BONUS = 18
_COUNTERPLAY_SUPPRESSION_BONUS = 8
_COUNTERPLAY_LINE_PENALTY = 10
_KING_CUTOFF_BONUS = 10
_ENEMY_PASSER_SUPPRESSION_BONUS = 12
_SEVENTH_RANK_PRESSURE_BONUS = 30
_MINOR_LANE_SUPPORT_BONUS = 12
_MINOR_EDGE_DRIFT_PENALTY = 12
_HEAVY_SIDE_DRIFT_PENALTY = 12
_BETTER_SIDE_PLAN_SWITCH_PENALTY = 24
_ANTI_QUEEN_TRADE_PENALTY = 50
_ANTI_QUEEN_TRADE_MIN_LEAD = 400  # 4 pawns
_LOW_MATERIAL_KING_LEAD_BONUS = 14
_LOW_MATERIAL_MAIN_PASSER_BONUS = 24
_LOW_MATERIAL_PROMOTION_BONUS = 96
_LOW_MATERIAL_MISSED_PROMOTION_PENALTY = 120
_LOW_MATERIAL_SIDE_PAWN_PENALTY = 18
_LOW_MATERIAL_PREMATURE_PUSH_PENALTY = 64
_LOW_MATERIAL_TRADE_BONUS = 240
_LOW_MATERIAL_CUTOFF_BONUS = 42
_CONVERSION_DISTANCE_PRESSURE_BONUS = 12
_TRIVIAL_CONVERSION_TRANSITION_BONUS = 54
